//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioConfiguracionesModernas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tema_claro_rb {
            get {
                return ((bool)(this["tema_claro_rb"]));
            }
            set {
                this["tema_claro_rb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tema_oscuro_rb {
            get {
                return ((bool)(this["tema_oscuro_rb"]));
            }
            set {
                this["tema_oscuro_rb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool skin_color_ambar {
            get {
                return ((bool)(this["skin_color_ambar"]));
            }
            set {
                this["skin_color_ambar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_azul {
            get {
                return ((bool)(this["skin_color_azul"]));
            }
            set {
                this["skin_color_azul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_morado_int {
            get {
                return ((bool)(this["skin_color_morado_int"]));
            }
            set {
                this["skin_color_morado_int"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_rosa {
            get {
                return ((bool)(this["skin_color_rosa"]));
            }
            set {
                this["skin_color_rosa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_cian {
            get {
                return ((bool)(this["skin_color_cian"]));
            }
            set {
                this["skin_color_cian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_naranja_int {
            get {
                return ((bool)(this["skin_color_naranja_int"]));
            }
            set {
                this["skin_color_naranja_int"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_indigo {
            get {
                return ((bool)(this["skin_color_indigo"]));
            }
            set {
                this["skin_color_indigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_gris_azul {
            get {
                return ((bool)(this["skin_color_gris_azul"]));
            }
            set {
                this["skin_color_gris_azul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_verde {
            get {
                return ((bool)(this["skin_color_verde"]));
            }
            set {
                this["skin_color_verde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_gris {
            get {
                return ((bool)(this["skin_color_gris"]));
            }
            set {
                this["skin_color_gris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_rojo {
            get {
                return ((bool)(this["skin_color_rojo"]));
            }
            set {
                this["skin_color_rojo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_morado {
            get {
                return ((bool)(this["skin_color_morado"]));
            }
            set {
                this["skin_color_morado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_verde_clar {
            get {
                return ((bool)(this["skin_color_verde_clar"]));
            }
            set {
                this["skin_color_verde_clar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_lima {
            get {
                return ((bool)(this["skin_color_lima"]));
            }
            set {
                this["skin_color_lima"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_verde_azul {
            get {
                return ((bool)(this["skin_color_verde_azul"]));
            }
            set {
                this["skin_color_verde_azul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_marron {
            get {
                return ((bool)(this["skin_color_marron"]));
            }
            set {
                this["skin_color_marron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_naranja {
            get {
                return ((bool)(this["skin_color_naranja"]));
            }
            set {
                this["skin_color_naranja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_amarillo {
            get {
                return ((bool)(this["skin_color_amarillo"]));
            }
            set {
                this["skin_color_amarillo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skin_color_azul_clar {
            get {
                return ((bool)(this["skin_color_azul_clar"]));
            }
            set {
                this["skin_color_azul_clar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool text_color_white {
            get {
                return ((bool)(this["text_color_white"]));
            }
            set {
                this["text_color_white"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool text_color_black {
            get {
                return ((bool)(this["text_color_black"]));
            }
            set {
                this["text_color_black"] = value;
            }
        }
    }
}
